import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import VoronoiBackground from "./_components/VoronoiBackground";
import NavBar from "./_components/NavBar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-gray-800">
        <NavBar />
        <main className="relative z-10 flex min-h-screen items-center justify-center">
          <div className="rounded-lg bg-gray-900 bg-opacity-50 p-8 shadow-lg backdrop-blur-sm">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </div>
        </main>
        <VoronoiBackground />
      </body>
    </html>
  );
}
